//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiDemo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalSoccerEdit_
    {
        public int id { get; set; }
        public string Team_1 { get; set; }
        public string Team_2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> ML_Price { get; set; }
        public Nullable<double> C_205 { get; set; }
        public Nullable<double> Price___delta { get; set; }
        public Nullable<double> Column1 { get; set; }
        public Nullable<double> Price_Delta { get; set; }
        public string Result { get; set; }
        public string First_Half_Result { get; set; }
        public string Final_Score { get; set; }
        public Nullable<double> Shots { get; set; }
        public Nullable<double> SOG { get; set; }
        public Nullable<double> Dangerous_Attacks { get; set; }
        public Nullable<double> Attacks { get; set; }
        public Nullable<double> ACR { get; set; }
        public Nullable<double> Possession { get; set; }
        public Nullable<double> Card_Count { get; set; }
        public string Score_First___Yes_No_ { get; set; }
    }
}
